// COUNYT CASES
export const FETCH_COUNT_CASES = 'FETCH_COUNT_CASES'
export const RECEIVE_COUNT_CASES = 'RECEIVE_COUNT_CASES'
export const SUCCESS_COUNT_CASES = 'SUCCESS_COUNT_CASES'
export const FAILED_COUNT_CASES = 'FAILED_COUNT_CASES'

// COUNTRIES
export const FETCH_COUNTRIES = 'FETCH_COUNT_CASES'
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNT_CASES'
export const FAILED_COUNTRIES = 'FAILED_COUNT_CASES'
